## numpy数组基础 
### 参考：python数据科学手册 ， http://www.runoob.com/python3/python3-tuple.html

In [154]:
import array
import numpy as np

### 1 数组

#### 数组基本概念

In [155]:
# 数组基本上包含一个指向连续数据块的指针；数组中存储的数据固定类型，更高效。
A = array.array('i', range(10))

print(A)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [156]:
# 整型数组。
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [157]:
# NumPy要求数组必须包含同一类型的数据。如果类型不匹配，NumPy将会向上转换（如果可行）。
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [158]:
# 如果希望明确设置数组的数据类型，可以用dtype关键字：
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [159]:
# NumPy数组可以被指定为多维的
# 嵌套列表构成的多维数组
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

#### 创建数组

In [160]:
# 值都是0的数组：创建一个长度为10的数组，数组的值都是0
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [161]:
# 数组的值都是1的数组：创建一个3×5的浮点型数组，数组的值都是1
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [162]:
# 数组的值都是3.14的数组：创建一个3×5的浮点型数组，数组的值都是3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [163]:
# 根据范围和步长生成数组：从0开始，到20结束，步长为2（它和内置的range()函数类似）
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [164]:
 # 线性分布数组：创建一个5个元素的数组，这5个数均匀地分配到0~1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [165]:
# 随机数数组：创建一个3×3的、在0~1均匀分布的随机数组成的数组
np.random.random((3, 3))

array([[0.94220946, 0.75669552, 0.16274307],
       [0.14335517, 0.94037331, 0.34616466],
       [0.02516554, 0.65385804, 0.71920571]])

In [166]:
# 正态分布随机数数组：创建一个3×3的、均值为0、方差为1的正态分布的随机数数组
np.random.normal(0, 1, (3, 3))

array([[ 0.35815457,  0.0737325 , -0.94059745],
       [ 2.01126738,  0.37761423, -0.26502948],
       [-0.22730369, -1.03889089, -0.43743573]])

In [167]:
# 随机整型数组：创建一个3×3的、 [0, 10)区间的随机整型数组
np.random.randint(0, 10, (3, 3))

array([[6, 5, 8],
       [5, 7, 6],
       [5, 8, 5]])

In [168]:
# 单位矩阵：创建一个3×3的单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [169]:
# 未初始化的数组：创建一个由3个整型数组成的未初始化的数组
# 数组的值是内存空间中的任意值
np.empty(3)

array([1., 1., 1.])

### 2 元组

#### 创建元组

In [170]:
# 与列表类似，元组的元素不能修改; 元组使用小括号，列表使用方括号。
tup=(1,2,3,4,5,6)
print(tup)

(1, 2, 3, 4, 5, 6)


In [171]:
l=['Google', 'Taobao', 'Baidu']
tup=tuple(l)
print(tup)

('Google', 'Taobao', 'Baidu')


In [172]:
# 创建空元组
tup = ()

In [173]:
# 元组中只包含一个元素时，需要在元素后面添加逗号，否则括号会被当作运算符使用：
tup = (50,) # 加上逗号，类型为元组
print(type(tup))

tup = (50)  # 不加逗号，类型为整型
print(type(tup))

<class 'tuple'>
<class 'int'>


#### 访问元组

In [174]:
# 使用下标索引来访问元组中的值
tup1 = ('Google', 1997, 2000)
print ("tup1[0]: ", tup1[0])

tup1[0]:  Google


In [175]:
# 使用下标索引范围来访问元组中的值
tup2 = (1, 2, 3, 4, 5, 6, 7 )
print ("tup2[1:5]: ", tup2[1:5])

tup2[1:5]:  (2, 3, 4, 5)


In [176]:
# 反向读取；读取倒数第二个元素
tup = ('Google', 1997, 2000)
tup[-2]

1997

In [177]:
# 截取元素，从第二个开始后的所有元素
tup[1:]

(1997, 2000)

#### 删除元组

In [178]:
tup = ('Google', 1997, 2000)
print (tup)

del tup;

('Google', 1997, 2000)


#### 元组运算符

In [179]:
# 计算元组元素个数
len((1, 2, 3))

3

In [180]:
# 返回元组中元素最大值
max((1, 2, 3))

3

In [181]:
# 返回元组中元素最小值
min((1, 2, 3))

1

In [182]:
# 连接
(1, 2, 3) + (4, 5, 6)

(1, 2, 3, 4, 5, 6)

In [183]:
# 复制
('Hi!',) * 4

('Hi!', 'Hi!', 'Hi!', 'Hi!')

In [184]:
# 元素是否存在
3 in (1, 2, 3)

True

In [185]:
# 迭代
for x in (1, 2, 3): 
    print (x,)

1
2
3


### 3 列表

In [186]:
# 包含一个指向指针块的指针，这其中的每一个指针对应一个完整的 Python 对象。
# 每个列表元素是一个包含数据和类型信息的完整结构体，而且列表可以用任意类型的数据填充。
list1 = ['Google', 1997, 2000];
list2 = [1, 2, 3, 4, 5 ];
list3 = ["a", "b", "c", "d"];

#### 访问列表

In [187]:
# 使用下标索引来访问列表中的值
print ("list1[0]: ", list1[0])

list1[0]:  Google


In [188]:
# 使用下标索引范围来访问列表中的值
print ("list2[1:5]: ", list2[1:5])

list2[1:5]:  [2, 3, 4, 5]


In [189]:
# 从右侧开始读取倒数第二个元素
list1[-2]

1997

In [190]:
# 输出从第二个元素开始后的所有元素
list1[1:]

[1997, 2000]

#### 删除列表元素

In [191]:
# 使用 del 语句来删除列表的的元素
list1 = ['Google', 1997, 2000]
del list1[2]

print (list1)

['Google', 1997]


#### 运算符

In [192]:
# 长度
len([1, 2, 3])

3

In [193]:
# 返回元组中元素最大值
max([1, 2, 3])

3

In [194]:
# 返回元组中元素最小值
min([1, 2, 3])

1

In [195]:
# 连接
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [196]:
# 复制
['Hi!'] * 4

['Hi!', 'Hi!', 'Hi!', 'Hi!']

In [197]:
# 元素是否存在于列表中
3 in [1, 2, 3]

True

In [198]:
# 迭代
for x in [1, 2, 3]: print(x, end=" ")

1 2 3 