## numpy数组基础 
### 参考：python数据科学手册

In [83]:
import numpy as np 

### 1 数组的属性

In [84]:
np.random.seed(0) # 设置随机数种子

x1 = np.random.randint(10, size=6) # 一维数组
x2 = np.random.randint(10, size=(3, 4)) # 二维数组
x3 = np.random.randint(10, size=(3, 4, 5)) # 三维数组

#每个数组有 nidm（数组的维度）、 shape（数组每个维度的大小）和 size（数组的总大小）
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [85]:
#dtype，它是数组的数据类型; itemsize,每个数组元素字节大小; nbytes表示数组总字节大小
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


### 2 数组的索引

In [86]:
#获取单个元素
#通过中括号指定索引获取第 i 个值（从 0 开始计数）
print(x1)
print(x1[0])

[5 0 3 3 7 9]
5


In [87]:
#获取数组的末尾索引，可以用负值索引
print(x1[-1])
print(x1[-2])

9
7


In [88]:
#多维数组中，可以用逗号分隔的索引元组获取元素
print(x2)

print(x2[0, 0])
print(x2[2, 0])
print(x2[2, -1])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
3
1
7


In [89]:
#用索引方式修改元素值
x2[0, 0] = 12
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [90]:
#NumPy 数组是固定类型的。这意味着当你试图将一个浮点值插入一个整型数组时，浮点值会被截短成整型。
#并且这种截短是自动完成的，不会给你提示或警告
x1[0] = 3.14159 # 这将被截短
print(x1)

[3 0 3 3 7 9]


### 3 数组的切分

#### 一维子数组

In [91]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [92]:
x[:5] # 前五个元素

array([0, 1, 2, 3, 4])

In [93]:
x[5:] # 索引五之后的元素

array([5, 6, 7, 8, 9])

In [94]:
x[4:7] # 中间的子数组

array([4, 5, 6])

In [95]:
x[::2] # 每隔一个元素

array([0, 2, 4, 6, 8])

In [96]:
x[1::2] # 每隔一个元素，从索引1开始

array([1, 3, 5, 7, 9])

In [97]:
x[::-1] # 所有元素，逆序的

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [98]:
x[5::-2] # 从索引5开始每隔一个元素逆序

array([5, 3, 1])

#### 多维子数组

In [99]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [100]:
x2[:2, :3] # 两行，三列

array([[12,  5,  2],
       [ 7,  6,  8]])

In [101]:
x2[:3, ::2] # 所有行，每隔一列

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [102]:
#子数组维度也可以同时被逆序：
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### 获取数组的行和列

In [103]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [104]:
print(x2[:, 0]) # x2的第一列

[12  7  1]


In [105]:
print(x2[0, :]) # x2的第一行

[12  5  2  4]


In [106]:
print(x2[0]) #等于x2[0, :]

[12  5  2  4]


#### 非副本视图的子数组

In [107]:
#数组切片返回的是数组数据的视图，而不是数值数据的副本。
#在Python 列表中，切片是值的副本。
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [108]:
#在处理非常大的数据集时，可以获取或处理这些数据集的片段，而不用复制底层的数据缓存。
#从中抽取一个 2×2 的子数组：
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [109]:
#如果修改这个子数组，将会看到原始数组也被修改了
x2_sub[0, 0] = 99
print(x2_sub)
print(x2)

[[99  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


#### 创建数组的副本

In [110]:
#复制数组里的数据或子数组
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [111]:
#如果修改这个子数组，原始的数组不会被改变：
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)
print(x2)

[[42  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### 4 数组的变形

#### 通过 reshape() 函数

In [112]:
#将数字 1~9 放入一个 3×3 的矩阵中，可以采用如下方法：
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [113]:
x = np.array([1, 2, 3])

# 通过变形获得的行向量
x.reshape((1, 3))

array([[1, 2, 3]])

In [114]:
# 通过变形获得的列向量
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

#### 切片操作中利用 newaxis 关键字

In [115]:
# 通过newaxis获得的行向量
x[np.newaxis, :]

array([[1, 2, 3]])

In [116]:
# 通过newaxis获得的列向量
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### 5 数组拼接和分裂

#### 数组的拼接

In [117]:
#拼接两个数组
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [118]:
#一次性拼接两个以上数组
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [119]:
#二维数组的拼接：
grid = np.array([[1, 2, 3],
[4, 5, 6]])

# 沿着第一个轴拼接
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [120]:
# 沿着第一个轴拼接（从0开始索引）
np.concatenate([grid, grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [121]:
# 沿着第二个轴拼接（从0开始索引）
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [122]:
# 垂直栈数组
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
[6, 5, 4]])

np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [123]:
# 水平栈数组
y = np.array([[99],
[99]])

np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

#### 数组的分裂

In [124]:
#指定分裂点，N 分裂点会得到 N + 1 个子数组
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [125]:
grid = np.arange(16).reshape((4, 4))
print(grid)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [126]:
#水平分裂
upper, lower = np.vsplit(grid, [2])

print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [127]:
#垂直分裂
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
