## NumPy通用函数
### 参考：python数据科学手册

##### 通过通用函数用向量的方式进行计算几乎总比用Python循环实现的计算更加有效，尤其是当数组很大时，只要你看到Python脚本中有这样的循环，就应该考虑能否用向量方式替换这个循环。
##### 通用函数另外一个非常有用的特性是它能操作不同大小和形状的数组，一组这样的操作被称为广播（ broadcasting）。

In [1]:
import numpy as np 

### 1 数组的运算

In [2]:
# 用到了Python原生的算术运算符，标准的加、减、乘、除
x = np.arange(4)
print("x =", x)

print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) #地板除法运算

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [3]:
# 逻辑非，**表示的指数运算符，%表示的模运算符
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [4]:
# 算术运算符组合
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

### 2 NumPy实现的算术运算符

运算符 |  对应的通用函数      |         描述
-|-|-
+   |  np.add              |       加法运算（即 1 + 1 = 2）
-   |  np.subtract         |       减法运算（即 3 - 2 = 1）
-   |  np.negative         |       负数运算（即 -2）
*   |  np.multiply         |       乘法运算（即 2 * 3 = 6）
/   |  np.divide           |       除法运算（即 3 / 2 = 1.5）
//  |  np.floor_divide     |      地板除法运算（ floor division，即 3 // 2 = 1）
**  |  np.power            |      指数运算（即 2 ** 3 = 8）
%   |  np.mod              |       模 / 余数（即 9 % 4 = 1）

In [5]:
# NumPy内置函数例子
print("x =", x)
np.add(x, 2)

x = [0 1 2 3]


array([2, 3, 4, 5])

### 3 NumPy通用函数
##### 通用函数有两种存在形式： 一元通用函数（ unary ufunc）对单个输入操作， 二元通用函数（ binary ufunc）对两个输入操作。

#### 绝对值

In [6]:
# 绝对值
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [7]:
# 通用函数np.absolute，该函数也可以用别名np.abs来访问
np.abs(x)
np.absolute(x)

array([2, 1, 0, 1, 2])

In [8]:
# abs当处理复数时，绝对值返回的是该复数的幅度
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

#### 三角函数

In [9]:
theta = np.linspace(0, np.pi, 3)

# 三角函数
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [10]:
# 逆三角函数
x = [-1, 0, 1]
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


#### 指数和对数

In [11]:
# 指数运算
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("2^x =", np.power(2, x))
print("3^x =", np.power(3, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
2^x = [2 4 8]
3^x = [ 3  9 27]


In [12]:
# 指数运算的逆运算，即对数运算
# 最基本的np.log给出的是以自然数为底数的对数。也可以以2为底数或者以10为底数的对数。
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [13]:
# 一些特殊的版本，对于非常小的输入值可以保持较好的精度
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


#### 专用的通用函数

##### NumPy 还提供了很多通用函数，包括双曲三角函数、比特位运算、比较运算符、弧度转化为角度的运算、取整和求余运算，等等

In [14]:
from scipy import special

In [15]:
# Gamma函数（广义阶乘， generalized factorials）和相关函数
x = [1, 5, 10]

print("gamma(x) =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))

print("beta(x, 2) =", special.beta(x, 2))

gamma(x) = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2) = [0.5        0.03333333 0.00909091]


In [16]:
# 误差函数（高斯积分）
# 它的实现和它的逆实现
x = np.array([0, 0.3, 0.7, 1.0])

print("erf(x) =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x) = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


### 4 通用函数高级特性

#### 指定输出

In [17]:
# 对于较大的数组，通过慎重使用out参数将能够有效节约内存。
# 所有的通用函数都可以通过out参数来指定计算结果的存放位置：
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)

print(y)

[ 0. 10. 20. 30. 40.]


In [18]:
# 将计算结果写入指定数组的每隔一个元素的位置：
x = np.arange(5)
y = np.zeros(10)
np.power(2, x, out=y[::2])

print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


#### 聚合

In [19]:
# 一个reduce方法会对给定的元素和操作重复执行，直至得到单个的结果。
# 在一些特殊情况中， NumPy 提供了专用的函数（ np.sum、 np.prod、 np.cumsum、np.cumprod ） ，它们也可以实现以上 reduce 的功能
# 对 add 通用函数调用 reduce 方法会返回数组中所有元素的和：
x = np.arange(1, 6)
np.add.reduce(x)

15

In [20]:
# 对multiply通用函数调用reduce方法会返回数组中所有元素的乘积：
np.multiply.reduce(x)

120

In [21]:
# 如果需要存储每次计算的中间结果，可以使用accumulate：
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [22]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

#### 外积

In [23]:
# 任何通用函数都可以用outer方法获得两个不同输入数组所有元素对的函数运算结果。
# 这意味着你可以用一行代码实现一个乘法表：
x = np.arange(1, 10)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])